{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "deployment.serviceAccountName" . }}
  labels:
{{ include "deployment.labels" . | indent 4 }}
{{- end -}}
