{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "SagaSphere_GraphQL.serviceAccountName" . }}
  labels:
{{ include "SagaSphere_GraphQL.labels" . | indent 4 }}
{{- end -}}
